### PR TITLE
Redesign/loggedout homepage

### PR DESCRIPTION
**Pull request by sscarberry**
## Problem
Stlye issues that did not match the design.

## Solution
updated the styling and added more styling to better match the design. Updated content in contentful to also be in line with design.

### CODE REVIEW

**Review by dholloran-ample — CHANGES_REQUESTED** [review]
@sscarberry - I have a few things

1. You had Our Best Content to be more dynamic checked. I unchecked it. I think we should fix the title but the more dynamic piece could be a separate story
2. Lessen top padding in Current Series looks to be lessened from `~170px` to `~150px`. The request was for a 2/3 of the current size `~110px`
3. Let's go ahead and fix 30 Day Challenge Section styling off from the design
4. Let's go ahead and fix Articles, Podcasts, and more subhead spacing off
5. If 30 Day Challenge Section styling off from design is easy let's go ahead and do that or split it out into a new task

**Comment by sscarberry** [comment]
> @sscarberry - I have a few things
> 
> 1. You had Our Best Content to be more dynamic checked. I unchecked it. I think we should fix the title but the more dynamic piece could be a separate story
> 2. Lessen top padding in Current Series looks to be lessened from `~170px` to `~150px`. The request was for a 2/3 of the current size `~110px`
> 3. Let's go ahead and fix 30 Day Challenge Section styling off from the design
> 4. Let's go ahead and fix Articles, Podcasts, and more subhead spacing off
> 5. If 30 Day Challenge Section styling off from design is easy let's go ahead and do that or split it out into a new task

1.) I check this because I updated the content in contenful to match what the request was. This is determined by a content type called featued content in contentful that can be easily updated by a content manager. I should have noted this in the PR. If we desire to have _no_ interaction with this and truly be dynamic we should make a separate card.

2.) The modifications you are mentioning are related to the larger screen size. The card you unchecked is referring to mobile. I reduced the mobile padding to be close to the 2/3 mark.

3.-5) I can take care of these.

**Comment by sscarberry** [comment]
Screen Shot 2022-01-19 at 12 58 49 PM
This is the current padding on Mobile for current series section.

**Comment by dholloran-ample** [comment]
> Details

@sscarberry 🤦🏻‍♂️ You're right sorry I missed that the padding was on mobile.

**Review by dholloran-ample — CHANGES_REQUESTED** [review]
@sscarberry - Almost there one more thing

The ready to start your adventure at the bottom is still off spacing-wise. The weird thing is on production it is fine. If we could get back to how it looks on production I think we would be good the biggest issue is the spacing.

screenshot 2022-01-19 at 16 10 32

**Review by dholloran-ample — APPROVED** [review]

**Pull request merged**
